services:
  mariadb:
    container_name: tessEBs_db
    image: mariadb
    env_file:
      - .env
    command: --max_allowed_packet=32505856
    restart: always
    volumes:
      - ./tessEBs.20250323.sql:/docker-entrypoint-initdb.d/dbimport.sql
      - ./dbdata:/var/lib/mysql
      - /tmp/tessEBs/mysqld:/var/run/mysqld
    healthcheck:
      test: ["CMD", "mariadb", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "use", "${MYSQL_DATABASE}"]
      timeout: 10s
      retries: 10
    ports:
      - "${MYSQL_PORT}:3306"

  django:
    container_name: tessEBs_django
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./catalog/static:/srv/www/tessEBs/catalog/static
      - ./static:/srv/www/tessEBs/static
      - /tmp/tessEBs/mysqld:/var/run/mysqld
    working_dir: /srv/www/tessEBs
    command: sh -c "uwsgi --http :8080 --wsgi-file tessEBs/wsgi.py --master --processes 4 --threads 2 --static-map2 /static=/srv/www/tessEBs"
    restart: always
    ports:
      - "8080:8080"
    environment:
      DJANGO_SETTINGS_MODULE: tessEBs.settings
      PYTHONUNBUFFERED: 1
      DEBUG: 0
      ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
volumes:
  dbdata:
