# Generated by Django 3.0.4 on 2020-03-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tess_id', models.IntegerField(verbose_name='tess id')),
                ('ra', models.FloatField(null=True, verbose_name='ra')),
                ('dec', models.FloatField(null=True, verbose_name='dec')),
                ('glon', models.FloatField(null=True, verbose_name='galactic longitude')),
                ('glat', models.FloatField(null=True, verbose_name='galactic latitude')),
                ('Tmag', models.FloatField(null=True, verbose_name='tess magnitude')),
                ('teff', models.FloatField(null=True, verbose_name='effective temperature')),
                ('logg', models.FloatField(null=True, verbose_name='surface gravity')),
                ('abun', models.FloatField(null=True, verbose_name='metallicity')),
            ],
        ),
        migrations.CreateModel(
            name='EB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_catalog', models.BooleanField(verbose_name='in catalog')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('date_modified', models.DateTimeField(null=True, verbose_name='date modified')),
                ('source', models.CharField(choices=[('FFI', 'Full Frame Image (FFI)'), ('TPF', 'Target Pixel File (TPF)'), ('LCF', 'Light Curve File (LCF)')], default='LCF', max_length=3)),
                ('bjd0', models.FloatField(null=True, verbose_name='bjd0')),
                ('bjd0_uncert', models.FloatField(null=True, verbose_name='bjd0 uncertainty')),
                ('period', models.FloatField(null=True, verbose_name='orbital period')),
                ('period_uncert', models.FloatField(null=True, verbose_name='period uncertainty')),
                ('morph_coeff', models.FloatField(null=True, verbose_name='morphology coefficient')),
                ('lc', models.FilePathField(default='', verbose_name='light curve')),
                ('tic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.TIC')),
            ],
        ),
    ]
