# Generated by Django 3.0.4 on 2020-03-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eb',
            name='lc',
        ),
    ]
