# Generated by Django 3.0.4 on 2020-03-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_eb_lc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eb',
            name='bjd0',
            field=models.FloatField(blank=True, null=True, verbose_name='bjd0'),
        ),
        migrations.AlterField(
            model_name='eb',
            name='bjd0_uncert',
            field=models.FloatField(blank=True, null=True, verbose_name='bjd0 uncertainty'),
        ),
        migrations.AlterField(
            model_name='eb',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='eb',
            name='morph_coeff',
            field=models.FloatField(blank=True, null=True, verbose_name='morphology coefficient'),
        ),
        migrations.AlterField(
            model_name='eb',
            name='period',
            field=models.FloatField(blank=True, null=True, verbose_name='orbital period'),
        ),
        migrations.AlterField(
            model_name='eb',
            name='period_uncert',
            field=models.FloatField(blank=True, null=True, verbose_name='period uncertainty'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='Tmag',
            field=models.FloatField(blank=True, null=True, verbose_name='tess magnitude'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='abun',
            field=models.FloatField(blank=True, null=True, verbose_name='metallicity'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='dec'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='glat',
            field=models.FloatField(blank=True, null=True, verbose_name='galactic latitude'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='glon',
            field=models.FloatField(blank=True, null=True, verbose_name='galactic longitude'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='logg',
            field=models.FloatField(blank=True, null=True, verbose_name='surface gravity'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='ra'),
        ),
        migrations.AlterField(
            model_name='tic',
            name='teff',
            field=models.FloatField(blank=True, null=True, verbose_name='effective temperature'),
        ),
    ]
