# Generated by Django 3.0.4 on 2020-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200319_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='signal_id',
            field=models.IntegerField(default=1, verbose_name='signal id'),
        ),
    ]
