# Generated by Django 3.0.4 on 2020-03-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_eb_signal_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eb',
            constraint=models.UniqueConstraint(fields=('tic', 'signal_id'), name='eb_id'),
        ),
    ]
