# Generated by Django 3.0.4 on 2020-03-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
