# Generated by Django 3.0.4 on 2020-03-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_datasource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='PlanetHunters', max_length=32),
            preserve_default=False,
        ),
    ]
