# Generated by Django 3.0.4 on 2020-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200320_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSource',
            new_name='DataOrigin',
        ),
        migrations.AddField(
            model_name='eb',
            name='origin',
            field=models.ManyToManyField(to='catalog.DataOrigin'),
        ),
    ]
