# Generated by Django 3.0.4 on 2020-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200320_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.IntegerField(verbose_name='sector id')),
                ('date_start', models.DateTimeField(verbose_name='start date')),
                ('date_end', models.DateTimeField(verbose_name='end date')),
                ('spacecraft_ra', models.FloatField(verbose_name='spacecraft R.A.')),
                ('spacecraft_dec', models.FloatField(verbose_name='spacecraft dec')),
                ('spacecraft_roll', models.FloatField(verbose_name='spacecraft roll')),
                ('camera1_ra', models.FloatField(verbose_name='camera 1 R.A.')),
                ('camera1_dec', models.FloatField(verbose_name='camera 1 dec')),
                ('camera1_roll', models.FloatField(verbose_name='camera 1 roll')),
                ('camera2_ra', models.FloatField(verbose_name='camera 2 R.A.')),
                ('camera2_dec', models.FloatField(verbose_name='camera 2 dec')),
                ('camera2_roll', models.FloatField(verbose_name='camera 2 roll')),
                ('camera3_ra', models.FloatField(verbose_name='camera 3 R.A.')),
                ('camera3_dec', models.FloatField(verbose_name='camera 3 dec')),
                ('camera3_roll', models.FloatField(verbose_name='camera 3 roll')),
                ('camera4_ra', models.FloatField(verbose_name='camera 4 R.A.')),
                ('camera4_dec', models.FloatField(verbose_name='camera 4 dec')),
                ('camera4_roll', models.FloatField(verbose_name='camera 4 roll')),
            ],
        ),
    ]
