# Generated by Django 3.0.4 on 2020-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='date_end',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='date_start',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
