# Generated by Django 3.0.4 on 2020-05-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200506_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='sectors',
            field=models.ManyToManyField(to='catalog.Sector'),
        ),
    ]
