# Generated by Django 3.0.4 on 2020-07-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_eb_sectors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataOrigin',
            new_name='InfoOrigin',
        ),
    ]
