# Generated by Django 3.0.4 on 2020-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200722_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoOrigin',
            new_name='Origin',
        ),
    ]
