# Generated by Django 3.0.4 on 2020-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200723_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemerisSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('author', models.CharField(max_length=64)),
                ('reference', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ephemeris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('bjd0', models.FloatField(blank=True, null=True, verbose_name='bjd0')),
                ('bjd0_uncert', models.FloatField(blank=True, null=True, verbose_name='bjd0 uncertainty')),
                ('period', models.FloatField(blank=True, null=True, verbose_name='orbital period')),
                ('period_uncert', models.FloatField(blank=True, null=True, verbose_name='period uncertainty')),
                ('source', models.ManyToManyField(to='catalog.EphemerisSource')),
            ],
        ),
        migrations.AddField(
            model_name='eb',
            name='ephemeris',
            field=models.ManyToManyField(blank=True, to='catalog.Ephemeris'),
        ),
    ]
