# Generated by Django 3.0.4 on 2020-09-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200918_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eb',
            name='ephemeris',
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='eb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ephemerides', to='catalog.EB'),
            preserve_default=False,
        ),
    ]
