# Generated by Django 3.0.4 on 2020-09-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200919_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eb',
            options={'verbose_name_plural': 'EBs'},
        ),
        migrations.AlterModelOptions(
            name='ephemeris',
            options={'verbose_name_plural': 'Ephemerides'},
        ),
        migrations.RemoveField(
            model_name='eb',
            name='bjd0',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='bjd0_uncert',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='period',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='period_uncert',
        ),
    ]
