# Generated by Django 3.0.4 on 2020-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200919_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tic',
            options={'verbose_name_plural': 'TICs'},
        ),
        migrations.AddField(
            model_name='eb',
            name='manual_bjd0',
            field=models.FloatField(blank=True, null=True, verbose_name='bjd0'),
        ),
        migrations.AddField(
            model_name='eb',
            name='manual_period',
            field=models.FloatField(blank=True, null=True, verbose_name='orbital period'),
        ),
    ]
