# Generated by Django 3.0.4 on 2020-10-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201013_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeris',
            name='tic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ephemerides', to='catalog.TIC'),
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='triage_period',
            field=models.CharField(default='period', max_length=16),
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='triage_status',
            field=models.CharField(default='triage', max_length=16),
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='triage_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='triaged on'),
        ),
    ]
