# Generated by Django 3.0.4 on 2020-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeris',
            name='triage_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
