# Generated by Django 3.0.4 on 2020-12-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_ephemeris_triage_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tic',
            name='tess_id',
            field=models.BigIntegerField(verbose_name='tess id'),
        ),
    ]
