# Generated by Django 3.0.4 on 2021-01-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20201201_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephemeris',
            name='tic',
        ),
    ]
