# Generated by Django 3.0.4 on 2021-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_remove_ephemeris_tic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tic',
            name='pmdec',
            field=models.FloatField(blank=True, null=True, verbose_name='proper motion in dec [mas/yr]'),
        ),
        migrations.AddField(
            model_name='tic',
            name='pmra',
            field=models.FloatField(blank=True, null=True, verbose_name='proper motion in ra [mas/yr]'),
        ),
    ]
