# Generated by Django 3.0.4 on 2021-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20210121_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eb',
            old_name='manual_bjd0',
            new_name='bjd0',
        ),
        migrations.RenameField(
            model_name='eb',
            old_name='manual_period',
            new_name='period',
        ),
        migrations.AddField(
            model_name='eb',
            name='bjd0_uncert',
            field=models.FloatField(blank=True, null=True, verbose_name='bjd0 uncertainty'),
        ),
        migrations.AddField(
            model_name='eb',
            name='ephem_2g_logprob',
            field=models.FloatField(blank=True, null=True, verbose_name='2-gaussian logp'),
        ),
        migrations.AddField(
            model_name='eb',
            name='ephem_pf_logprob',
            field=models.FloatField(blank=True, null=True, verbose_name='polyfit logp'),
        ),
        migrations.AddField(
            model_name='eb',
            name='period_uncert',
            field=models.FloatField(blank=True, null=True, verbose_name='period uncertainty'),
        ),
    ]
