# Generated by Django 3.0.4 on 2021-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20210312_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='morph_dist',
            field=models.FloatField(blank=True, null=True, verbose_name='morphology distance'),
        ),
    ]
