# Generated by Django 3.0.4 on 2021-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20210818_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='ambiguous',
            field=models.BooleanField(default=False, verbose_name='ambiguous'),
        ),
        migrations.AddField(
            model_name='eb',
            name='heartbeat',
            field=models.BooleanField(default=False, verbose_name='heartbeat star'),
        ),
        migrations.AddField(
            model_name='eb',
            name='insufficient',
            field=models.BooleanField(default=False, verbose_name='insufficient cycles'),
        ),
        migrations.AddField(
            model_name='eb',
            name='pulscomp',
            field=models.BooleanField(default=False, verbose_name='pulsating component'),
        ),
    ]
