# Generated by Django 3.0.4 on 2021-09-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20210903_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='multi',
            field=models.BooleanField(default=False, verbose_name='multiperiodic system'),
        ),
    ]
