# Generated by Django 3.0.4 on 2021-09-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_eb_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eb',
            name='prim_depth_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse depth from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='prim_depth_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse depth from the polyfit model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='prim_pos_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse position from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='prim_pos_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse position from the polyfit model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='prim_width_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse width from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='prim_width_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='primary eclipse width from the polyfit model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_depth_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse depth from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_depth_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse depth from the polyfit model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_pos_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse position from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_pos_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse position from the polyfit model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_width_2g',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse width from the 2-gaussian model'),
        ),
        migrations.AddField(
            model_name='eb',
            name='sec_width_pf',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='secondary eclipse width from the polyfit model'),
        ),
    ]
