# Generated by Django 3.0.4 on 2021-11-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_tic_gaia_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eb',
            name='morph_dist',
        ),
    ]
