# Generated by Django 3.2.13 on 2022-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_remove_eb_morph_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eb',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='ephemeris',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
