# Generated by Django 3.2.13 on 2022-04-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20220418_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeris',
            name='tic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ephemerides', to='catalog.tic'),
        ),
    ]
