# Generated by Django 3.2.13 on 2022-04-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_ephemeris_tic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeris',
            name='tic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ephemerides', to='catalog.tic'),
        ),
    ]
