# Generated by Django 3.2.13 on 2022-04-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_ephemeris_tic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephemeris',
            name='eb',
        ),
    ]
