# Generated by Django 3.2.13 on 2022-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_remove_ephemeris_eb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tic',
            name='datatype',
            field=models.CharField(choices=[('FFI', 'Full Frame Image (FFI)'), ('TPF', 'Target Pixel File (TPF)'), ('LCF', 'Light Curve File (LCF)')], default='LCF', max_length=3),
        ),
    ]
