# Generated by Django 3.2.13 on 2022-11-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_tic_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tic',
            name='asas_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tic',
            name='kepler_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='kepler id'),
        ),
    ]
