# Generated by Django 3.2.18 on 2023-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_tic_asas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tic',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='catalog.Sector'),
        ),
    ]
