# Generated by Django 3.2.18 on 2023-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_tic_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tic',
            name='gaia_dr3_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='gaia dr3 id'),
        ),
    ]
