# Generated by Django 3.2.18 on 2024-03-19 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_tic_gaia_dr3_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLS_run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(verbose_name='duration')),
                ('min_eclipses', models.IntegerField(verbose_name='minimum number of eclipses')),
                ('pmin', models.FloatField(verbose_name='minimum period')),
                ('pmax', models.FloatField(verbose_name='maximum period')),
                ('period', models.FloatField(verbose_name='period')),
                ('bjd0', models.FloatField(verbose_name='time of first eclipse')),
                ('max_power', models.FloatField(verbose_name='maximum SPD power')),
                ('bls_logp', models.FloatField(verbose_name='log-likelihood for the first eclipse')),
                ('date_run', models.DateTimeField(auto_now_add=True, verbose_name='BLS run date')),
                ('depth', models.FloatField(verbose_name='eclipse depth')),
                ('depth_unc', models.FloatField(verbose_name='eclipse depth uncertainty')),
                ('depth_odd', models.FloatField(verbose_name='double-period odd eclipse depth')),
                ('depth_odd_unc', models.FloatField(verbose_name='double-period odd eclipse depth uncertainty')),
                ('depth_even', models.FloatField(verbose_name='double-period even eclipse depth')),
                ('depth_even_unc', models.FloatField(verbose_name='double-period even eclipse depth uncertainty')),
                ('depth_half', models.FloatField(verbose_name='half-period eclipse depth')),
                ('depth_half_unc', models.FloatField(verbose_name='half-period eclipse depth uncertainty')),
                ('tic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tic')),
            ],
        ),
    ]
