# Generated by Django 3.2.18 on 2024-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_bls_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='tic',
            name='provenances',
            field=models.ManyToManyField(blank=True, to='catalog.Provenance'),
        ),
    ]
