# Generated by Django 5.1.3 on 2024-12-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20241120_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ephemeris',
            name='source',
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='source',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='catalog.ephemerissource'),
            preserve_default=False,
        ),
    ]
