# Generated by Django 5.1.6 on 2025-02-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_eb_ephemeris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eb',
            name='bjd0',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='bjd0_uncert',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='ephem_2g_logprob',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='ephem_pf_logprob',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='period',
        ),
        migrations.RemoveField(
            model_name='eb',
            name='period_uncert',
        ),
    ]
